line-length = 88
target-version = "py312"

[format]
quote-style = "double"

[lint]
select = [
    "F",     # Pyflakes
    "W",     # pycodestyle warnings
    "E",     # pycodestyle errors
    "ASYNC", # flake8-async
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "S",     # flake8-bandit
    "SIM",   # flake8-simplify
    "Q",     # flake8-quotes
    "I",     # isort
    "UP",    # pyupgrade
    "RUF",   # Ruff-specific rules
]
ignore = [
    "F403",
    "F405",
    "E501",
    "ASYNC230",
    "ASYNC240",
    "RUF001",
    "RUF002",
    "RUF003",
]

[lint.per-file-ignores]
"strategy.py" = ["B027"]
"tests/**/*.py" = ["S101"]
